title: tepe.so
description: Technical documentation
theme: just-the-docs

url: https://tepelabs.github.io/

aux_links:
  tepe.so: https://tepe.so/
  X: https://x.com/tepe_labs
  Discord: https://discord.gg/MEw877x86p
